# Generated by Django 3.2.6 on 2021-08-15 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_r_in', models.IntegerField(default=0)),
                ('voltage_r_out', models.IntegerField(default=0)),
                ('current_r_in', models.IntegerField(default=0)),
                ('voltage_y_in', models.IntegerField(default=0)),
                ('voltage_y_out', models.IntegerField(default=0)),
                ('current_y_in', models.IntegerField(default=0)),
                ('voltage_b_in', models.IntegerField(default=0)),
                ('voltage_b_out', models.IntegerField(default=0)),
                ('current_b_in', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot.device')),
            ],
        ),
    ]
